[package]
name = "sse-server"
version = "0.0.2"
authors = ["Bevan Hunt <bevan@bevanhunt.com>"]
edition = "2018"
license = "MIT"
keywords = ["sse", "actix-web", "sse-server"]
description = "SSE server using Actix Web"
repository = "https://github.com/apibillme/sse-server"
readme = "README.md"

[dependencies]
actix-rt = "1.0.0"
actix-web = "2.0.0"
actix-cors = "0.2.0"
futures = "0.3.1"
tokio = "0.2.4"
sse-actix-web = "0.7.0"
serde = "1.0.103"
serde_json = "1.0.44"
serde_derive = "1.0.103"
json = "0.12.0"
sled = "0.30.3"
envy = "0.4.0"
env_logger = "0.6"
chrono = { version = "0.4.10", features = ["serde"] }
